# Generated by Django 2.2.4 on 2019-12-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendente',
            name='password',
        ),
    ]
