# Generated by Django 2.2.7 on 2019-11-18 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senha',
            name='hora_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 18, 15, 29, 57, 976040, tzinfo=utc)),
        ),
    ]
