# Generated by Django 2.2.4 on 2019-12-02 01:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191202_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senha',
            name='hora_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 2, 1, 58, 5, 785333, tzinfo=utc)),
        ),
    ]
