# Generated by Django 2.2.7 on 2019-11-18 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191118_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senha',
            name='hora_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 18, 18, 53, 16, 642091, tzinfo=utc)),
        ),
    ]
