# Generated by Django 2.2.7 on 2019-11-18 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191118_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senha',
            name='hora_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 18, 19, 59, 33, 777811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='statussenha',
            name='nome',
            field=models.CharField(default='Na fila', max_length=80),
        ),
    ]
