# Generated by Django 2.2.7 on 2019-11-18 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191118_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senha',
            name='hora_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 18, 20, 1, 25, 257854, tzinfo=utc)),
        ),
    ]
