# Generated by Django 2.2.4 on 2019-12-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191202_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='Campo',
            new_name='campi',
        ),
    ]
