# Generated by Django 2.2.7 on 2019-11-18 22:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191118_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senha',
            name='hora_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 18, 22, 32, 0, 594782, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='senha',
            name='senha',
            field=models.CharField(max_length=255),
        ),
    ]
