# Generated by Django 2.2.7 on 2019-12-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191202_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiche',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Em atendimento'),
        ),
    ]
