# Generated by Django 2.2.4 on 2019-11-18 22:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191118_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senha',
            name='hora_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 18, 22, 39, 2, 882979, tzinfo=utc)),
        ),
    ]
