# Generated by Django 2.2.4 on 2019-12-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191204_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='campus',
            new_name='nome',
        ),
    ]
