# Generated by Django 2.2.4 on 2019-12-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191204_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendente',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='atendente',
            old_name='Siape',
            new_name='siape',
        ),
    ]
