# Generated by Django 2.2.4 on 2019-12-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191205_1415'),
        ('api', '0008_auto_20191202_1931'),
    ]

    operations = [
    ]
