# Generated by Django 2.2.7 on 2019-12-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191202_1931'),
        ('api', '0010_auto_20191205_1415'),
    ]

    operations = [
    ]
