# Generated by Django 2.2.4 on 2019-12-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20191205_2028'),
        ('api', '0011_merge_20191205_1804'),
    ]

    operations = [
    ]
