# Generated by Django 2.2.7 on 2019-11-11 12:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id_atendente', models.IntegerField(primary_key=True, serialize=False)),
                ('Siape', models.IntegerField()),
                ('Nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id_campus', models.IntegerField(primary_key=True, serialize=False)),
                ('Campo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='StatusSenha',
            fields=[
                ('id_statusSenha', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id_senha', models.IntegerField(primary_key=True, serialize=False)),
                ('senha', models.IntegerField()),
                ('hora_data', models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 11, 12, 27, 7, 575434))),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Categoria')),
                ('fk_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StatusSenha')),
                ('fk_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Guiche',
            fields=[
                ('id_guiche', models.IntegerField(primary_key=True, serialize=False)),
                ('nmr_guiche', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
                ('fk_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id_atendimento', models.IntegerField(primary_key=True, serialize=False)),
                ('hora_data_ini', models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 11, 12, 27, 7, 577310))),
                ('hora_data_fim', models.DateTimeField()),
                ('fk_atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Atendente')),
                ('fk_guiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Guiche')),
                ('fk_senha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Senha')),
            ],
        ),
    ]
