# Generated by Django 2.2.7 on 2019-11-11 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='hora_data_ini',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='senha',
            name='hora_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 11, 14, 39, 51, 302444)),
        ),
    ]
